### ISSUE TITLE
FE + IN: Scraping results 

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-apple-cider#18]
- User can enter a url on the input for product scraping, select a list and hit "Add". 
- It will send a request to the backend which will initialize a scraping job and eventually return the scraping details to the client. 
- The frontend will show a dialog containing the scrape results (name, price of the product, among other details)
- The user can hit confirm to save those details or cancel. 
- If the user hits save, the product scraping details will be persisted on the db and added to the list

**Comment by adams-liu** [comment]
Wouldn't this task be dependent on task #6?
